Avoid redfine of IO_SIZE if made configurable
MariaDB/mariadb-connector-c pull request #265
Opened 2024-12-31 17:14 UTC by ericherman

If the server is to make IO_SIZE configurable, we need to avoid either redefining it, or defining it to be different.

See: https://github.com/MariaDB/server/pull/3726

2025-01-01 13:43 UTC, vuvova requested changes

2025-01-01 13:43 UTC, vuvova commented on include/ma_global.h
> +#endif
I don't like that, there's no reason — that I can see — why server's IO_SIZE should affect the client. I'd suggest to rename IO_SIZE in the libmariadb. See how it's used, perhaps a `NET_BUFF_ALIGN` could be a good name

2025-01-03 13:02 UTC, ericherman commented on include/ma_global.h
> +#endif
I would be perfectly happy to rename client constant instead as I also feel like these should be able to be distinct; @9E0R9 what do you think?

2025-01-05 08:59 UTC, ericherman commented on include/ma_global.h
> +#endif
I've updated and --force pushed

2025-01-05 10:16 UTC, vuvova approved these changes
look good to me

2025-01-05 16:24 UTC, closed without merging